// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCku3MLUobni-fbTPQUBg0WvPLsqZPoM3U',
    appId: '1:1029128336972:web:e5b8235c2acac69c40a6e9',
    messagingSenderId: '1029128336972',
    projectId: 'flutter-2478a',
    authDomain: 'flutter-2478a.firebaseapp.com',
    storageBucket: 'flutter-2478a.firebasestorage.app',
    measurementId: 'G-G91S95JQ3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADOzSrghZYsLCoWG-Ww2gQYhwIgDYjRnU',
    appId: '1:1029128336972:android:5b728109bc91f4f940a6e9',
    messagingSenderId: '1029128336972',
    projectId: 'flutter-2478a',
    storageBucket: 'flutter-2478a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjUsu5OyzQMU-WO3zwktVoeGywtiwddE4',
    appId: '1:1029128336972:ios:662b81214f7d725940a6e9',
    messagingSenderId: '1029128336972',
    projectId: 'flutter-2478a',
    storageBucket: 'flutter-2478a.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjUsu5OyzQMU-WO3zwktVoeGywtiwddE4',
    appId: '1:1029128336972:ios:662b81214f7d725940a6e9',
    messagingSenderId: '1029128336972',
    projectId: 'flutter-2478a',
    storageBucket: 'flutter-2478a.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCku3MLUobni-fbTPQUBg0WvPLsqZPoM3U',
    appId: '1:1029128336972:web:76a97928a98afba340a6e9',
    messagingSenderId: '1029128336972',
    projectId: 'flutter-2478a',
    authDomain: 'flutter-2478a.firebaseapp.com',
    storageBucket: 'flutter-2478a.firebasestorage.app',
    measurementId: 'G-E03XETF93H',
  );
}
